-- seed-universe.sql — generated by verify-universe.mjs on 2026-10-01T14:07:05.465Z
-- Greens only: 31 of 48 candidates. Blocked names live in universe-verified.json.
-- Apply:  npx wrangler d1 execute stock-market-db --local  --file=scripts/seed-universe.sql
--         npx wrangler d1 execute stock-market-db --remote --file=scripts/seed-universe.sql
INSERT INTO tickers (symbol, name, sector, status) VALUES ('AAPL', 'Apple Inc.', 'Technology', 'active') ON CONFLICT(symbol) DO UPDATE SET name=excluded.name, sector=excluded.sector, status='active';
INSERT INTO tickers (symbol, name, sector, status) VALUES ('PFE', 'Pfizer Inc.', 'Healthcare', 'active') ON CONFLICT(symbol) DO UPDATE SET name=excluded.name, sector=excluded.sector, status='active';
INSERT INTO tickers (symbol, name, sector, status) VALUES ('JNJ', 'Johnson & Johnson', 'Healthcare', 'active') ON CONFLICT(symbol) DO UPDATE SET name=excluded.name, sector=excluded.sector, status='active';
INSERT INTO tickers (symbol, name, sector, status) VALUES ('MSFT', 'Microsoft Corporation', 'Technology', 'active') ON CONFLICT(symbol) DO UPDATE SET name=excluded.name, sector=excluded.sector, status='active';
INSERT INTO tickers (symbol, name, sector, status) VALUES ('INTC', 'Intel Corp.', 'Technology', 'active') ON CONFLICT(symbol) DO UPDATE SET name=excluded.name, sector=excluded.sector, status='active';
INSERT INTO tickers (symbol, name, sector, status) VALUES ('GOOGL', 'Alphabet Inc.', 'Communication Services', 'active') ON CONFLICT(symbol) DO UPDATE SET name=excluded.name, sector=excluded.sector, status='active';
INSERT INTO tickers (symbol, name, sector, status) VALUES ('META', 'Meta Platforms, Inc.', 'Communication Services', 'active') ON CONFLICT(symbol) DO UPDATE SET name=excluded.name, sector=excluded.sector, status='active';
INSERT INTO tickers (symbol, name, sector, status) VALUES ('AMZN', 'Amazon.com, Inc.', 'Consumer Cyclical', 'active') ON CONFLICT(symbol) DO UPDATE SET name=excluded.name, sector=excluded.sector, status='active';
INSERT INTO tickers (symbol, name, sector, status) VALUES ('AMD', 'Advanced Micro Devices, Inc.', 'Technology', 'active') ON CONFLICT(symbol) DO UPDATE SET name=excluded.name, sector=excluded.sector, status='active';
INSERT INTO tickers (symbol, name, sector, status) VALUES ('KO', 'The Coca-Cola Company', 'Consumer Defensive', 'active') ON CONFLICT(symbol) DO UPDATE SET name=excluded.name, sector=excluded.sector, status='active';
INSERT INTO tickers (symbol, name, sector, status) VALUES ('PEP', 'PepsiCo, Inc.', 'Consumer Defensive', 'active') ON CONFLICT(symbol) DO UPDATE SET name=excluded.name, sector=excluded.sector, status='active';
INSERT INTO tickers (symbol, name, sector, status) VALUES ('SBUX', 'Starbucks Corporation', 'Consumer Cyclical', 'active') ON CONFLICT(symbol) DO UPDATE SET name=excluded.name, sector=excluded.sector, status='active';
INSERT INTO tickers (symbol, name, sector, status) VALUES ('NKE', 'NIKE, Inc.', 'Consumer Cyclical', 'active') ON CONFLICT(symbol) DO UPDATE SET name=excluded.name, sector=excluded.sector, status='active';
INSERT INTO tickers (symbol, name, sector, status) VALUES ('DIS', 'The Walt Disney Company', 'Communication Services', 'active') ON CONFLICT(symbol) DO UPDATE SET name=excluded.name, sector=excluded.sector, status='active';
INSERT INTO tickers (symbol, name, sector, status) VALUES ('NFLX', 'Netflix, Inc.', 'Communication Services', 'active') ON CONFLICT(symbol) DO UPDATE SET name=excluded.name, sector=excluded.sector, status='active';
INSERT INTO tickers (symbol, name, sector, status) VALUES ('TSLA', 'Tesla, Inc.', 'Consumer Cyclical', 'active') ON CONFLICT(symbol) DO UPDATE SET name=excluded.name, sector=excluded.sector, status='active';
INSERT INTO tickers (symbol, name, sector, status) VALUES ('NVDA', 'NVIDIA Corporation', 'Technology', 'active') ON CONFLICT(symbol) DO UPDATE SET name=excluded.name, sector=excluded.sector, status='active';
INSERT INTO tickers (symbol, name, sector, status) VALUES ('V', 'Visa Inc.', 'Financial Services', 'active') ON CONFLICT(symbol) DO UPDATE SET name=excluded.name, sector=excluded.sector, status='active';
INSERT INTO tickers (symbol, name, sector, status) VALUES ('JPM', 'JPMorgan Chase & Co.', 'Financial Services', 'active') ON CONFLICT(symbol) DO UPDATE SET name=excluded.name, sector=excluded.sector, status='active';
INSERT INTO tickers (symbol, name, sector, status) VALUES ('BAC', 'Bank of America Corporation', 'Financial Services', 'active') ON CONFLICT(symbol) DO UPDATE SET name=excluded.name, sector=excluded.sector, status='active';
INSERT INTO tickers (symbol, name, sector, status) VALUES ('WMT', 'Walmart Inc.', 'Consumer Defensive', 'active') ON CONFLICT(symbol) DO UPDATE SET name=excluded.name, sector=excluded.sector, status='active';
INSERT INTO tickers (symbol, name, sector, status) VALUES ('COST', 'Costco Wholesale Corporation', 'Consumer Defensive', 'active') ON CONFLICT(symbol) DO UPDATE SET name=excluded.name, sector=excluded.sector, status='active';
INSERT INTO tickers (symbol, name, sector, status) VALUES ('UNH', 'UnitedHealth Group Incorporated', 'Healthcare', 'active') ON CONFLICT(symbol) DO UPDATE SET name=excluded.name, sector=excluded.sector, status='active';
INSERT INTO tickers (symbol, name, sector, status) VALUES ('ABBV', 'AbbVie Inc.', 'Healthcare', 'active') ON CONFLICT(symbol) DO UPDATE SET name=excluded.name, sector=excluded.sector, status='active';
INSERT INTO tickers (symbol, name, sector, status) VALUES ('XOM', 'Exxon Mobil Corporation', 'Energy', 'active') ON CONFLICT(symbol) DO UPDATE SET name=excluded.name, sector=excluded.sector, status='active';
INSERT INTO tickers (symbol, name, sector, status) VALUES ('CVX', 'Chevron Corporation', 'Energy', 'active') ON CONFLICT(symbol) DO UPDATE SET name=excluded.name, sector=excluded.sector, status='active';
INSERT INTO tickers (symbol, name, sector, status) VALUES ('BA', 'The Boeing Company', 'Industrials', 'active') ON CONFLICT(symbol) DO UPDATE SET name=excluded.name, sector=excluded.sector, status='active';
INSERT INTO tickers (symbol, name, sector, status) VALUES ('GE', 'GE Aerospace', 'Industrials', 'active') ON CONFLICT(symbol) DO UPDATE SET name=excluded.name, sector=excluded.sector, status='active';
INSERT INTO tickers (symbol, name, sector, status) VALUES ('CSCO', 'Cisco Systems, Inc.', 'Technology', 'active') ON CONFLICT(symbol) DO UPDATE SET name=excluded.name, sector=excluded.sector, status='active';
INSERT INTO tickers (symbol, name, sector, status) VALUES ('ADBE', 'Adobe Inc.', 'Technology', 'active') ON CONFLICT(symbol) DO UPDATE SET name=excluded.name, sector=excluded.sector, status='active';
INSERT INTO tickers (symbol, name, sector, status) VALUES ('DAL', 'Delta Air Lines, Inc.', 'Industrials', 'active') ON CONFLICT(symbol) DO UPDATE SET name=excluded.name, sector=excluded.sector, status='active';
